import { Fonts, Colors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const cameraOverlayStyles = StyleSheet.create({
  maskContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  overlayTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "40%",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  overlayBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "40%",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  overlayLeft: {
    position: "absolute",
    top: "40%",
    bottom: "40%",
    left: 0,
    width: "12%",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  overlayRight: {
    position: "absolute",
    top: "40%",
    bottom: "40%",
    right: 0,
    width: "12%",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  cutoutContainer: {
    height: "100%",
    width: "100%",
    backgroundColor: "transparent",
  },
  cutoutTopLeft: {
    height: 2,
    width: "10%",
    top: "40%",
    left: "12%",
    position: "absolute",
  },
  cutoutLeftTop: {
    width: 2,
    height: "5%",
    top: "40%",
    left: "12%",
    position: "absolute",
  },
  cutoutTopRight: {
    height: 2,
    width: "10%",
    top: "40%",
    right: "12%",
    position: "absolute",
  },
  cutoutRightTop: {
    width: 2,
    height: "5%",
    top: "40%",
    right: "12%",
    position: "absolute",
  },
  cutoutRightBottom: {
    width: 2,
    height: "5%",
    bottom: "40%",
    right: "12%",
    position: "absolute",
  },
  cutoutBottomRight: {
    height: 2,
    width: "10%",
    bottom: "40%",
    right: "12%",
    position: "absolute",
  },
  cutoutLeftBottom: {
    width: 2,
    height: "5%",
    bottom: "40%",
    left: "12%",
    position: "absolute",
  },
  cutoutBottomLeft: {
    height: 2,
    width: "10%",
    bottom: "40%",
    left: "12%",
    position: "absolute",
  },
  camera: {
    flex: 1,
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    zIndex: 0,
  },
});

export const cameraStyles = ({ colorScheme }: { colorScheme?: keyof typeof Colors }) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors[colorScheme ?? "light"].background,
    },
    content: {
      flex: 1,
      padding: 24,
      gap: 32,
      paddingTop: 100,
      alignItems: "center",
      justifyContent: "center",
    },
    cameraTools: {
      position: "absolute",
      zIndex: 20,
      bottom: 120,
      alignSelf: "center",
      display: "flex",
      flexDirection: "row",
      gap: 12,
      backgroundColor: "transparent",
      elevation: 5,
    },
    textContainer: {
      flexDirection: "row",
      gap: 12,
      alignItems: "center",
      alignContent: "center",
      marginVertical: 8,
    },
    buttonsContainer: {
      gap: 16,
      marginTop: 24,
      width: "100%",
    },
    productTitle: {
      fontWeight: "bold",
      fontSize: 18,
      textTransform: "uppercase",
      fontFamily: Fonts.bold,
      color: Colors[colorScheme ?? "light"].text,
      flex: 1,
    },
    productSecond: {
      fontSize: 16,
      color: Colors[colorScheme ?? "light"].text,
      flex: 2,
      flexWrap: "wrap",
    },
  });
};
